export const FETCH_CURRENCIES = 'FETCH_CURRENCIES';
export const SUCCESS_CURRENCIES = 'SUCCESS_CURRENCIES';
export const ERROR_CURRENCIES = 'ERROR_CURRENCIES';

export const SET_EXPENSES = 'SET_EXPENSES';
